name: Deploy to Pods via Jump Host

on:
  push:
    branches:
      - github-actions-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via Jump Host
        uses: appleboy/ssh-action@master
        with:
          host: "52.172.45.176"
          username: "jumpuser"
          key: "jumpuser"
          script: |
            cd /home/ubuntu/deployment-scripts
            ./deploy_pods.sh
