name: Deploy Airflow DAGs to Stage (Using SSH Key)

on:
  push:
    branches:
      - main

jobs:
  deploy-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy DAGs to Stage Airflow VM (Using SSH Key for Target)
        # Set SSH_KNOWN_HOSTS to an empty string to disable host key checking
        env:
          SSH_KNOWN_HOSTS: ""
        uses: appleboy/ssh-action@v0.1.9
        with:
          # Target (Stage) host details
          host: "10.16.182.70"
          username: "wps"
          # Use the private key stored in your GitHub secret (TARGET_SSH_KEY)
          key: ${{ secrets.TARGET_SSH_KEY }}
          port: 22

          # Jump (Proxy) host details
          proxy_host: "52.172.45.176"
          proxy_port: 22
          proxy_username: "jumpuser"
          proxy_password: "jumpuser"

          script: |
            echo "Deploying DAGs to Stage Airflow VM..."
            # Rsync command: only updates or adds files from the repository's 'dags/' folder
            # to the remote directory (/opt/airflow/dags/) without deleting extra files.
            rsync -avz $GITHUB_WORKSPACE/dags/ /opt/airflow/dags/
            # Optionally, restart Airflow services if needed:
            # sudo systemctl restart airflow-scheduler
