name: Deploy to Pods via Jump Host

on:
  push:
    branches:
      - github-actions-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via Jump Host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JUMP_HOST }}
          username: ${{ secrets.JUMP_USER }}
          key: ${{ secrets.JUMP_SSH_KEY }}
          script: |
            cd /home/ubuntu/deployment-scripts
            ./deploy_pods.sh
